### ISSUE TITLE
Field suggestion improvements

### ISSUE THREAD

**Issue by gregmiret** [EtienneMiret/Registre#72] opened 2020-01-04 08:56 UTC
When registre provide fields suggestions (like owner, actors...), disable the browser suggestions so that users don't see double suggestions overlapping.

Also remove obsolete suggestions : typically when a typo is made with an entry then edited, the incorrect entry should not appear.

**Comment by EtienneMiret** [comment] 2022-04-30 17:03
> When registre provide fields suggestions (like owner, actors...), disable the browser suggestions so that users don't see double suggestions overlapping.

It seems this was always the case. Well, since commit 3b565c5e644da02c64bbff0036d88534cdd3e718, which was merged at the same time as the auto-completion feature. And according to [caniuse](https://caniuse.com/?search=autocomplete) disabling builtin auto-completion was supported for a long time. Do you have a reproduction case?

**Comment by gregmiret** [comment] 2022-04-30 18:56
Hum... you're right. I just tried and can't reproduce.

Maybe linked to the reported Chrome bug ?
https://bugs.chromium.org/p/chromium/issues/detail?id=468153#c29

**Comment by EtienneMiret** [comment] 2022-05-01 11:18
Yes, maybe. It seems at some point Chrome was ignoring this attribute.

Anyway, my plan is now to take advantage of the [datalist] element, so that the browser’s builtin auto-completion suggest appropriate values. This should provide a better UX.

Also, I will remove unused items (e.g. actors playing in zero referenced movies) from the suggestion list.

[datalist]: https://html.spec.whatwg.org/multipage/form-elements.html#the-datalist-element

**Closed** 2022-05-01 14:42 UTC
Labels: enhancement
